
title: Simon Schrottner - @aepfli
description: Bearded Austrian Guy who loves to code
author:
  name: Simon Schrottner - @aepfli
  email: simon.schrottner@netconomy.net
show_excerpts: false # set to true to show excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%d-%d"
  
  skin: solarized

  # generate social links in footer
  social_links:
    twitter: aepfli
    github:  aepfli
    facebook: simon.schrottner
    gitlab:
     - username: s.schrottner
       instance: gitlab.com
      
    stackoverflow: "3708208/simon-schrottner"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

